version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    ports:
      - '8080:8080'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
